---
- name: Exécuter le script uninstall_nginx.sh sur la machine cible
  hosts: node1
  become: yes
  tasks:
    - name: Copier le fichier depuis la machine localhost vers la machine node1 
      ansible.builtin.copy:
        src: /home/devops/ansible-git-repo/uninstall_nginx.sh  # Remplacez par le chemin local du script
        dest: /tmp/uninstall_nginx.sh
        mode: '0755'  # Définir les permissions d'exécution sur le script
#      delegate_to: localhost 

    - name: Exécuter le script uninstall_nginx.sh sur la machine node1
      script: /tmp/uninstall_nginx.sh
